import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import ACF from "../components/ACF";
import Events from "../components/Events";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ACF-Front</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ACF />
      <Events />
    </div>
  );
};

export default Home;
